export const SET_SUMMONER_QUEUES = 'SET_SUMMONER_QUEUES';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_SUMMONER = 'CLEAR_SUMMONER';
export const SET_SUMMONER_DETAILS = 'SET_SUMMONER_DETAILS';
export const SET_SUMMONER_MATCHES = 'SET_SUMMONER_MATCHES';
